import type { AgentTemplate } from './types';

export const agentTemplates: AgentTemplate[] = [
  // Litigation & Disputes
  {
    id: 'discovery-triage',
    name: 'Discovery Triage Agent',
    description: 'Reviews incoming documents overnight, tags by relevance and privilege, surfaces critical items for partner attention by 8am.',
    category: 'discovery-review',
    practiceAreas: ['litigation', 'disputes'],
    iconId: 'file-search',
    defaultPersonality: {
      riskTolerance: 2,
      communicationStyle: 3,
      thoroughness: 4,
      autonomy: 2,
    },
    defaultDataBoundary: {
      matters: 'specific',
      documents: 'full',
      financials: 'none',
      communications: 'none',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '4-6 hours per day',
    complexity: 'moderate',
    featured: true,
  },
  {
    id: 'deadline-horizon',
    name: 'Deadline Horizon Agent',
    description: 'Scans all matters for approaching deadlines, court dates, and limitation periods. Alerts at 14, 7, and 3 days out.',
    category: 'deadline-management',
    practiceAreas: ['litigation', 'disputes', 'corporate'],
    iconId: 'calendar-clock',
    defaultPersonality: {
      riskTolerance: 1,
      communicationStyle: 3,
      thoroughness: 5,
      autonomy: 4,
    },
    defaultDataBoundary: {
      matters: 'all',
      documents: 'none',
      financials: 'none',
      communications: 'calendar',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '2-3 hours per week',
    complexity: 'simple',
    featured: true,
  },
  {
    id: 'opposition-research',
    name: 'Opposition Research Agent',
    description: 'Tracks opposing counsel patterns, judge preferences, and relevant precedent cases for strategic advantage.',
    category: 'document-intelligence',
    practiceAreas: ['litigation', 'disputes'],
    iconId: 'search',
    defaultPersonality: {
      riskTolerance: 3,
      communicationStyle: 4,
      thoroughness: 5,
      autonomy: 3,
    },
    defaultDataBoundary: {
      matters: 'specific',
      documents: 'full',
      financials: 'none',
      communications: 'none',
      people: 'external',
      precedents: 'full',
    },
    estimatedTimeSavings: '3-5 hours per matter',
    complexity: 'advanced',
    featured: false,
  },
  // Corporate & M&A
  {
    id: 'contract-intelligence',
    name: 'Contract Intelligence Agent',
    description: 'Extracts key terms, identifies risk clauses, compares against firm playbook, and generates negotiation talking points.',
    category: 'document-intelligence',
    practiceAreas: ['corporate', 'banking'],
    iconId: 'file-text',
    defaultPersonality: {
      riskTolerance: 2,
      communicationStyle: 4,
      thoroughness: 5,
      autonomy: 2,
    },
    defaultDataBoundary: {
      matters: 'specific',
      documents: 'full',
      financials: 'none',
      communications: 'none',
      people: 'team',
      precedents: 'full',
    },
    estimatedTimeSavings: '2-4 hours per contract',
    complexity: 'moderate',
    featured: true,
  },
  {
    id: 'due-diligence-coordinator',
    name: 'Due Diligence Coordinator',
    description: 'Tracks document requests, identifies gaps in received materials, and escalates outstanding items.',
    category: 'intake-triage',
    practiceAreas: ['corporate', 'banking'],
    iconId: 'clipboard-check',
    defaultPersonality: {
      riskTolerance: 2,
      communicationStyle: 3,
      thoroughness: 4,
      autonomy: 3,
    },
    defaultDataBoundary: {
      matters: 'specific',
      documents: 'full',
      financials: 'summary',
      communications: 'email',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '5-8 hours per deal',
    complexity: 'moderate',
    featured: false,
  },
  {
    id: 'board-meeting-prep',
    name: 'Board Meeting Prep Agent',
    description: 'Analyses meeting agendas, assembles required documents, and prepares draft minutes templates.',
    category: 'document-intelligence',
    practiceAreas: ['corporate'],
    iconId: 'users',
    defaultPersonality: {
      riskTolerance: 1,
      communicationStyle: 2,
      thoroughness: 4,
      autonomy: 2,
    },
    defaultDataBoundary: {
      matters: 'specific',
      documents: 'full',
      financials: 'none',
      communications: 'calendar',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '2-3 hours per meeting',
    complexity: 'simple',
    featured: false,
  },
  // Billing & Revenue
  {
    id: 'time-reconstruction',
    name: 'Time Reconstruction Agent',
    description: 'Analyses email, document edits, calendar, and phone logs to suggest accurate billable entries.',
    category: 'billing-revenue',
    practiceAreas: ['all'],
    iconId: 'clock',
    defaultPersonality: {
      riskTolerance: 2,
      communicationStyle: 3,
      thoroughness: 4,
      autonomy: 3,
    },
    defaultDataBoundary: {
      matters: 'team',
      documents: 'summarise',
      financials: 'full',
      communications: 'both',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '30-45 minutes per day',
    complexity: 'moderate',
    featured: true,
  },
  {
    id: 'wip-shepherd',
    name: 'WIP Shepherd Agent',
    description: 'Chases aged unbilled time, prepares partner narratives, and triggers billing workflows.',
    category: 'billing-revenue',
    practiceAreas: ['all'],
    iconId: 'dollar-sign',
    defaultPersonality: {
      riskTolerance: 3,
      communicationStyle: 3,
      thoroughness: 3,
      autonomy: 4,
    },
    defaultDataBoundary: {
      matters: 'team',
      documents: 'none',
      financials: 'full',
      communications: 'email',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '2-4 hours per week',
    complexity: 'simple',
    featured: false,
  },
  {
    id: 'leakage-detective',
    name: 'Leakage Detective Agent',
    description: 'Compares actual activity to recorded time, identifies under-recording patterns by lawyer and matter type.',
    category: 'billing-revenue',
    practiceAreas: ['all'],
    iconId: 'trending-down',
    defaultPersonality: {
      riskTolerance: 2,
      communicationStyle: 4,
      thoroughness: 5,
      autonomy: 2,
    },
    defaultDataBoundary: {
      matters: 'all',
      documents: 'summarise',
      financials: 'full',
      communications: 'both',
      people: 'firm',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '$10-50K recovered monthly',
    complexity: 'advanced',
    featured: false,
  },
  // Compliance & Risk
  {
    id: 'compliance-sentinel',
    name: 'Compliance Sentinel Agent',
    description: 'Monitors policy compliance, detects potential breaches, and scans regulatory horizon for changes.',
    category: 'compliance-risk',
    practiceAreas: ['regulatory', 'banking', 'corporate'],
    iconId: 'shield',
    defaultPersonality: {
      riskTolerance: 1,
      communicationStyle: 2,
      thoroughness: 5,
      autonomy: 3,
    },
    defaultDataBoundary: {
      matters: 'all',
      documents: 'full',
      financials: 'summary',
      communications: 'email',
      people: 'firm',
      precedents: 'full',
    },
    estimatedTimeSavings: 'Risk mitigation',
    complexity: 'advanced',
    featured: true,
  },
  {
    id: 'conflict-check',
    name: 'Conflict Check Agent',
    description: 'Screens new matters for conflicts, analyses relationships, and recommends information barriers.',
    category: 'compliance-risk',
    practiceAreas: ['all'],
    iconId: 'alert-triangle',
    defaultPersonality: {
      riskTolerance: 1,
      communicationStyle: 2,
      thoroughness: 5,
      autonomy: 1,
    },
    defaultDataBoundary: {
      matters: 'all',
      documents: 'none',
      financials: 'none',
      communications: 'none',
      people: 'firm',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: '1-2 hours per matter',
    complexity: 'moderate',
    featured: false,
  },
  {
    id: 'matter-health-monitor',
    name: 'Matter Health Monitor',
    description: 'Continuously scores matter health, surfaces early warning indicators, and alerts partners to deteriorating matters.',
    category: 'compliance-risk',
    practiceAreas: ['all'],
    iconId: 'activity',
    defaultPersonality: {
      riskTolerance: 2,
      communicationStyle: 3,
      thoroughness: 4,
      autonomy: 4,
    },
    defaultDataBoundary: {
      matters: 'team',
      documents: 'summarise',
      financials: 'summary',
      communications: 'both',
      people: 'team',
      precedents: 'practice-group',
    },
    estimatedTimeSavings: 'Proactive risk management',
    complexity: 'moderate',
    featured: true,
  },
];

export function getTemplatesByCategory(category: string): AgentTemplate[] {
  if (category === 'all') return agentTemplates;
  return agentTemplates.filter(t => t.category === category || t.practiceAreas.includes(category));
}

export function getFeaturedTemplates(): AgentTemplate[] {
  return agentTemplates.filter(t => t.featured);
}

export function getTemplateById(id: string): AgentTemplate | undefined {
  return agentTemplates.find(t => t.id === id);
}
